dittto_security_login:
    path:     /login
    defaults: { _controller: DitttoSecurityBundle:Security:login }

dittto_security_check:
    path:     /check
    defaults: { _controller: DitttoSecurityBundle:Security:check }

dittto_security_logout:
    path:     /logout
    defaults: { _controller: DitttoSecurityBundle:Security:logout }

