dittto_security_home:
    path:     /
    defaults: { _controller: DitttoSecurityBundle:Security:index }

dittto_security_login:
    path:     /login
    defaults: { _controller: DitttoSecurityBundle:Security:login }

dittto_security_check:
    path:     /check
    defaults: { _controller: DitttoSecurityBundle:Security:check }

dittto_security_recovery-link:
    path:     /recovery-link
    defaults: { _controller: DitttoSecurityBundle:Security:recoveryLink }

dittto_security_reset-password:
    path:     /reset-password/{token}/{encyIdentifier}
    defaults: { _controller: DitttoSecurityBundle:Security:resetPassword }

