#dittto_user_homepage:
#    path:     /
#    defaults: { _controller: DitttoUserBundle:Default:index }

dittto_user_profile:
    path: /user/profile
    defaults: { _controller: DitttoUserBundle:Default:profile }

dittto_user_update_password:
    path: /user/password
    defaults: { _controller: DitttoUserBundle:Default:updatePassword }
