dittto_recognition:
    resource: "@DitttoRecognitionBundle/Resources/config/routing.yml"
    prefix:   /

dittto_security:
    resource: "@DitttoSecurityBundle/Resources/config/routing.yml"
    prefix:   /

dittto_user:
    resource: "@DitttoUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"