dittto_recognition_dashboard:
    path:     /dashboard
    defaults: { _controller: DitttoRecognitionBundle:Default:dashboard }

dittto_recognition_recognise_user:
    path:     /recognise
    defaults: { _controller: DitttoRecognitionBundle:Default:recognise }
